version: "3.7"

services:
  # Reader Service
  reader:
    env_file:
      - .env
    image: petitrobert/reader
    build:
      context: services/reader
    ports:
      - "${READER_SERVICE_PORT}:${READER_SERVICE_PORT}"

  # Database Handler Service
  database:
    env_file:
      - .env
    image: petitrobert/node-services
    build:
      context: services/node-services
    ports:
      - "${DATABASE_SERVICE_PORT}:${DATABASE_SERVICE_PORT}"
    entrypoint: ["node", "database/main.js"]

  # REST API Service
  api-gateway:
    env_file:
      - .env
    image: petitrobert/node-services
    build:
      context: services/node-services
    expose:
      - "${REST_API_SERVICE_PORT}"
    ports:
      - "${REST_API_SERVICE_PORT}:${REST_API_SERVICE_PORT}"
    entrypoint: ["node", "api-gateway/main.js"]
    links:
      - database
      - reader

  # Front Service
  front:
    env_file:
      - .env
    image: petitrobert/front
    build:
      context: services/front
    ports:
      - "${FRONT_SERVICE_PORT}:80"
    links:
      - api-gateway
