name: Release PetitRoBERT

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}

      - name: Build the whole project.
        run: ./build.sh

      - name: Push Base Node
        run: docker push petitrobert/base-node:latest

      - name: Push Base Rust
        run: docker push petitrobert/base-rust:latest

      - name: Push Reader Build Stage
        run: docker push petitrobert/reader:latest-build

      - name: Publish Reader Prod
        run: docker push petitrobert/reader:latest

      - name: Publish API Build Stage
        run: docker push petitrobert/api-gateway:latest-build

      - name: Publish API Prod
        run: docker push petitrobert/api-gateway:latest

      - name: Publish Front Build Stage
        run: docker push petitrobert/front:latest-build

      - name: Publish Front Prod
        run: docker push petitrobert/front:latest
